- hosts: server
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy configuration nginx
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 8080;
              location / {
                  proxy_pass http://localhost:5000;
              }
          }

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
